[package]
name = "maximizer"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = {version = "0.10"}

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
criterion = "0.3"

[profile.release]
lto = true
debug = true

[[bench]]
name = "maximum_matching"
harness = false
